# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EA_Slope
                                 A QGIS plugin
 function provides for estimating the equal area slopes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-06
        copyright            : (C) 2021 by WSP Global & The University and Queensland
        email                : ray.shi@wsp.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EA_Slope class from file EA_Slope.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .EA_Slope import EA_Slope
    return EA_Slope(iface)
