# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EA_SlopeDialog
                                 A QGIS plugin
 function provides for estimating the equal area slopes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-06
        git sha              : $Format:%H$
        copyright            : (C) 2021 by WSP Global & The University and Queensland
        email                : ray.shi@wsp.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'EA_Slope_dialog_base.ui'))


class EA_SlopeDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(EA_SlopeDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.vMapLayerComboBox.setFilters(QgsMapLayerProxyModel.VectorLayer)
        self.rMapLayerComboBox.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.toolButton.clicked.connect(self.getSaveFilename)
        #self.buttonBox.accepted.connect(self.m)

    def getSaveFilename(self):
        fn = QtWidgets.QFileDialog.getSaveFileName(self,'save file')[0]
        self.lineEdit.setText(fn)
